name: Release Package
run-name: ${{ format('{0}',  inputs.release_type == 'Snapshot' && 'Publish pre-release' || format('Release {0}', inputs.release_type))}} Package by @${{ github.actor }}  
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot
      publish_to_maven:
        description: 'True to publish the artifacts to maven repository, false to skip the step'
        default: false
        required: false
        type: boolean

jobs:
  build-publish-package:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/v2-shared-java-publish-versioned-package.yaml@tjm-UID2-2324-new-shared-java-package-pipeline
    with: 
      release_type: ${{ inputs.release_type }}
      publish_to_maven: ${{ inputs.publish_to_maven }}
    secrets: inherit

    